#!/usr/bin/env node
// Generates the TypeScript/zod and Go outputs from schemas/*.schema.json.
//
// The schemas are the source of truth. Nothing under ts/src/gen or gen is
// edited by hand; `--check` fails when a regeneration would change them, so
// CI catches a schema edit that forgot to regenerate.
//
// TypeScript: each schema is dereferenced (external $refs to common.v1 are
// inlined) and converted with json-schema-to-zod. Go: structs are produced
// by go-jsonschema (run through `go run`); runtime validation in Go does not
// come from those structs but from the schema files themselves, embedded and
// checked with santhosh-tekuri/jsonschema (see contracts.go).
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMAS = join(ROOT, 'schemas');
const TS_GEN = join(ROOT, 'ts', 'src', 'gen');
const GO_GEN = join(ROOT, 'gen');
const GO_JSONSCHEMA = 'github.com/atombender/go-jsonschema@v0.20.0';
const check = process.argv.includes('--check');

const HEADER = '// Generated by scripts/generate.mjs from schemas/. Do not edit.\n';

function camel(name) {
  return name.replace(/[-.](\w)/g, (_, c) => c.toUpperCase());
}

function pascal(name) {
  const c = camel(name);
  return c[0].toUpperCase() + c.slice(1);
}

function schemaFiles() {
  return readdirSync(SCHEMAS).filter((f) => f.endsWith('.schema.json') && !f.startsWith('common.')).sort();
}

async function generateTs() {
  const outputs = new Map();
  const names = [];
  for (const file of schemaFiles()) {
    const base = file.replace(/\.schema\.json$/, ''); // e.g. candle-snapshot-manifest.v1
    const schema = await $RefParser.dereference(join(SCHEMAS, file));
    delete schema.$id;
    delete schema.$schema;
    // Named $defs become their own exports when the document is a oneOf of
    // them (queue messages); otherwise the document itself is the export.
    const exports = [];
    const ident = camel(base.replace(/\.v(\d+)$/, 'V$1'));
    if (schema.anyOf && schema.$defs && Object.keys(schema.$defs).every((k) => schema.anyOf.some((o) => o === schema.$defs[k]))) {
      for (const [defName, def] of Object.entries(schema.$defs)) {
        const defIdent = `${ident}${pascal(defName)}`;
        exports.push(`export const ${defIdent} = ${jsonSchemaToZod(def, { module: 'none', noImport: true })};\nexport type ${pascal(defIdent)} = z.infer<typeof ${defIdent}>;`);
      }
      exports.push(`export const ${ident} = z.union([${Object.keys(schema.$defs).map((d) => `${ident}${pascal(d)}`).join(', ')}]);\nexport type ${pascal(ident)} = z.infer<typeof ${ident}>;`);
    } else {
      const { $defs, ...rest } = schema;
      exports.push(`export const ${ident} = ${jsonSchemaToZod(rest, { module: 'none', noImport: true })};\nexport type ${pascal(ident)} = z.infer<typeof ${ident}>;`);
    }
    outputs.set(join(TS_GEN, `${camel(base)}.ts`), `${HEADER}import { z } from 'zod';\n\n${exports.join('\n\n')}\n`);
    names.push({ base, ident, file: camel(base) });
  }
  const index = `${HEADER}${names.map((n) => `export * from './${n.file}.js';`).join('\n')}\n\nexport const SCHEMA_FILES = ${JSON.stringify(Object.fromEntries(names.map((n) => [n.ident, `${n.base}.schema.json`])), null, 2)} as const;\n`;
  outputs.set(join(TS_GEN, 'index.ts'), index);
  return outputs;
}

// go-jsonschema does not follow $refs into a sibling file, so it is fed
// fully dereferenced copies written to a temporary directory. File names are
// kept because the generator derives the root type name from them.
async function generateGo() {
  const outputs = new Map();
  const tmp = mkdtempSync(join(tmpdir(), 'heisentick-contracts-'));
  try {
    const args = ['run', GO_JSONSCHEMA, '--package', 'gen', '--only-models', '--capitalization', 'ID', '--capitalization', 'URL', '--output', '-'];
    for (const file of schemaFiles()) {
      const schema = await $RefParser.dereference(join(SCHEMAS, file));
      const base = file.replace(/\.schema\.json$/, '');
      const path = join(tmp, file);
      writeFileSync(path, JSON.stringify(schema));
      args.push('--schema-root-type', `${schema.$id}=${pascal(base.replace(/\.v(\d+)$/, 'V$1'))}`, path);
    }
    const goSource = execFileSync('go', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    outputs.set(join(GO_GEN, 'types.go'), `${HEADER}${goSource}`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
  return outputs;
}

function apply(outputs) {
  let drift = [];
  for (const [path, content] of outputs) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === content) continue;
    drift.push(path.replace(`${ROOT}/`, ''));
    if (!check) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content);
    }
  }
  return drift;
}

const tsOutputs = await generateTs();
if (!check) rmSync(TS_GEN, { recursive: true, force: true });
const drift = [...apply(tsOutputs), ...apply(await generateGo())];
if (check && drift.length) {
  console.error(`generated outputs are stale; run pnpm run generate:\n- ${drift.join('\n- ')}`);
  process.exit(1);
}
console.log(check ? 'generated outputs are current' : `wrote ${tsOutputs.size + 1} generated file(s)`);
